import React,{useEffect,useMemo,useState}from'react';
import{settingsApi,type ConfigSchema,type CustomEndpoint,type EnvInfo,type Session}from'./api';
import{SETTINGS_SECTIONS,fieldTitle,getPath,inputValue,setPath,visibleFields}from'./lib/settings-model.mjs';

type Props={sessions?:Session[];onClose:()=>void};
type Section=(typeof SETTINGS_SECTIONS)[number];
const SENSITIVE='••••••••';

function ConfigField({name,config,schema,onSaved}:{name:string;config:Record<string,unknown>;schema:ConfigSchema;onSaved:(name:string,value:unknown)=>Promise<void>}){
 const spec=schema.fields[name]||{type:'string'},current=getPath(config,name),[value,setValue]=useState<any>(current??''),[state,setState]=useState('');
 useEffect(()=>setValue(current??''),[current]);
 const save=async(next=value)=>{setState('saving');try{const typed=inputValue(next,spec.type);await onSaved(name,typed);setState('saved');setTimeout(()=>setState(''),1200)}catch{setState('error')}};
 const id='setting-'+name.replaceAll('.','-');
 if(spec.type==='boolean')return <label className="setting-row setting-toggle" htmlFor={id}><span><b>{fieldTitle(name)}</b><small>{spec.description}</small></span><input id={id} type="checkbox" checked={Boolean(value)} onChange={e=>{setValue(e.target.checked);void save(e.target.checked)}}/><i/></label>;
 const list=spec.type==='list'?Array.isArray(value)?value.join(', '):String(value??''):value;
 return <label className="setting-row" htmlFor={id}><span><b>{fieldTitle(name)}</b><small>{spec.description}</small></span><div className="setting-control">{spec.type==='select'&&Array.isArray(spec.options)&&spec.options.length<120?<select id={id} value={String(value??'')} onChange={e=>{setValue(e.target.value);void save(e.target.value)}}>{spec.options.map(x=><option key={String(x)} value={String(x)}>{String(x)||'Mặc định'}</option>)}</select>:<input id={id} type={spec.type==='number'?'number':'text'} min={spec.min} max={spec.max} value={String(list??'')} onChange={e=>setValue(e.target.value)} onBlur={()=>void save()} onKeyDown={e=>{if(e.key==='Enter')void save()}}/>}<em className={state}>{state==='saving'?'Đang lưu…':state==='saved'?'Đã lưu':state==='error'?'Lỗi':''}</em></div></label>
}

function Credentials({env,reload}:{env:Record<string,EnvInfo>;reload:()=>Promise<void>}){
 const rows=useMemo(()=>Object.entries(env).filter(([,v])=>!v.channel_managed).sort((a,b)=>Number(b[1].is_set)-Number(a[1].is_set)||a[0].localeCompare(b[0])),[env]);
 const[query,setQuery]=useState(''),[editing,setEditing]=useState<string|null>(null),[value,setValue]=useState(''),[busy,setBusy]=useState('');
 const shown=rows.filter(([key,v])=>(key+' '+(v.provider_label||'')+' '+(v.description||'')).toLowerCase().includes(query.toLowerCase())).slice(0,120);
 const save=async(key:string)=>{if(!value)return;setBusy(key);try{await settingsApi.setEnv(key,value);setEditing(null);setValue('');await reload()}finally{setBusy('')}};
 const clear=async(key:string)=>{if(!confirm(`Xóa ${key}?`))return;setBusy(key);try{await settingsApi.deleteEnv(key);await reload()}finally{setBusy('')}};
 return <><div className="settings-lead"><h2>API Keys</h2><p>Credential được lưu vào .env chính chủ của Hermes. Pocket không có chức năng xem lại secret.</p></div><input className="settings-search" placeholder="Tìm provider hoặc biến môi trường…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="credential-list">{shown.map(([key,info])=><section className="credential" key={key}><div><b>{info.provider_label||key}</b><code>{key}</code><small>{info.description}</small></div><span className={info.is_set?'configured':''}>{info.is_set?(info.redacted_value||SENSITIVE):'Chưa cấu hình'}</span>{editing===key?<div className="credential-edit"><input autoFocus type="password" placeholder="Nhập giá trị mới" value={value} onChange={e=>setValue(e.target.value)}/><button disabled={busy===key} onClick={()=>void save(key)}>Lưu</button><button onClick={()=>setEditing(null)}>Hủy</button></div>:<div className="credential-actions"><button onClick={()=>{setEditing(key);setValue('')}}>{info.is_set?'Thay':'Thêm'}</button>{info.is_set&&<button className="danger" disabled={busy===key} onClick={()=>void clear(key)}>Xóa</button>}</div>}</section>)}</div></>
}

function CustomEndpoints(){
 const[rows,setRows]=useState<CustomEndpoint[]>([]),[form,setForm]=useState({name:'',base_url:'',model:'',api_key:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>setRows((await settingsApi.customEndpoints()).endpoints||[]);useEffect(()=>{void load()},[]);
 const save=async()=>{if(!form.name||!/^https?:\/\//.test(form.base_url)||!form.model){setError('Cần tên, URL http(s) và model.');return}setBusy(true);setError('');try{await settingsApi.saveCustomEndpoint({...form,api_key:form.api_key||undefined});setForm({name:'',base_url:'',model:'',api_key:''});await load()}catch{setError('Không lưu được endpoint.')}finally{setBusy(false)}};
 return <section className="custom-endpoints"><h3>Endpoint tùy chỉnh</h3><p>API key chỉ được gửi khi lưu; Pocket không tải lại giá trị đã có.</p><div className="endpoint-form"><label><span>Tên endpoint</span><input placeholder="Ví dụ: Local" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Base URL</span><input inputMode="url" autoCapitalize="none" spellCheck={false} placeholder="https://…/v1" value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})}/></label><label><span>Model</span><input autoCapitalize="none" spellCheck={false} placeholder="Ví dụ: provider/model" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label><span>API key (tùy chọn)</span><input aria-label="API key endpoint" type="password" autoComplete="new-password" placeholder="Chỉ nhập khi cần thay" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})}/></label><button disabled={busy} onClick={()=>void save()}>Thêm endpoint</button></div>{error&&<small role="alert">{error}</small>}<div className="endpoint-list">{rows.map(x=><div key={x.id}><span><b>{x.name}</b><code>{x.base_url}</code><small>{x.model}</small></span><button onClick={async()=>{await settingsApi.activateCustomEndpoint(x.id);await load()}}>Dùng</button><button className="danger" onClick={async()=>{if(confirm(`Xóa ${x.name}?`)){await settingsApi.deleteCustomEndpoint(x.id);await load()}}}>Xóa</button></div>)}</div></section>
}

function Appearance(){const[mode,setMode]=useState(localStorage.getItem('hp:theme')||'dark'),[compact,setCompact]=useState(localStorage.getItem('hp:compact')!=='false');const apply=(m:string)=>{setMode(m);localStorage.setItem('hp:theme',m);document.documentElement.dataset.theme=m};const density=(v:boolean)=>{setCompact(v);localStorage.setItem('hp:compact',String(v));document.documentElement.classList.toggle('comfortable',!v)};return <><div className="settings-lead"><h2>Giao diện</h2><p>Tùy chỉnh riêng cho Pocket trên thiết bị này.</p></div><div className="choice-grid">{['system','dark','light'].map(x=><button className={mode===x?'selected':''} onClick={()=>apply(x)} key={x}>{x==='system'?'Theo hệ thống':x==='dark'?'Tối':'Sáng'}</button>)}</div><label className="setting-row setting-toggle"><span><b>Mật độ gọn</b><small>Giữ nhiều nội dung hơn trên màn hình iPhone.</small></span><input type="checkbox" checked={compact} onChange={e=>density(e.target.checked)}/><i/></label></>}

function DevicePanel({section,sessions=[]}:{section:Section;sessions?:Session[]}){
 if(section.id==='notifications'){const supported='Notification'in window,[permission,setPermission]=useState(supported?Notification.permission:'unsupported');return <><div className="settings-lead"><h2>Thông báo</h2><p>Thông báo hoàn thành tác vụ trên thiết bị này.</p></div><div className="capability-card"><b>Quyền trình duyệt</b><span>{permission}</span>{supported&&<button onClick={async()=>setPermission(await Notification.requestPermission())}>Cấp quyền</button>}</div></>}
 if(section.id==='keybinds')return <><div className="settings-lead"><h2>Phím tắt</h2><p>Phím tắt phù hợp trình duyệt/PWA.</p></div><div className="shortcut-list"><span><kbd>Ctrl</kbd> + <kbd>Enter</kbd><b>Gửi tin nhắn</b></span><span><kbd>Esc</kbd><b>Đóng Cài đặt</b></span></div></>;
 if(section.id==='sessions')return <><div className="settings-lead"><h2>Chat đã lưu trữ</h2><p>{sessions.length} session canonical đang hiển thị trong Pocket.</p></div><div className="session-summary">{sessions.slice(0,60).map(s=><div key={s.id}><b>{s.title||'Chưa đặt tên'}</b><small>{s.id}</small></div>)}</div></>;
 if(section.id==='about')return <><div className="about-pocket"><div className="mark">H</div><h2>Hermes Pocket</h2><p>PWA dùng chung canonical session, memory, skills, tools và cấu hình với Hermes Desktop.</p><code>Settings authority: Hermes config.yaml + .env</code></div></>;
 const details:{[key:string]:[string,string]}={billing:['Usage & Billing','Số liệu usage/cost thuộc backend Hermes; Pocket không tạo bộ đếm song song.'],gateway:['Gateway','Gateway đang chạy độc lập. Thay đổi connection/runtime từ xa được khóa để tránh làm gián đoạn IDE.'],plugins:['Plugins','Plugin được quản lý bởi Hermes Desktop/CLI. Pocket giữ menu và trạng thái nhưng không mở filesystem trên iPhone.']};const d=details[section.id]||[section.label,'Capability này thuộc máy Windows và không có API web an toàn tương đương.'];return <><div className="settings-lead"><h2>{d[0]}</h2><p>{d[1]}</p></div><div className="capability-card readonly"><b>Desktop capability</b><span>Chỉ đọc trên Pocket</span><small>Không có nút giả và không tạo cấu hình song song.</small></div></>
}

export function Settings({sessions,onClose}:Props){const[active,setActive]=useState('model'),[config,setConfig]=useState<Record<string,unknown>>({}),[schema,setSchema]=useState<ConfigSchema>({fields:{},category_order:[]}),[env,setEnv]=useState<Record<string,EnvInfo>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');const section=SETTINGS_SECTIONS.find(x=>x.id===active)!;
 const reloadEnv=async()=>setEnv((await settingsApi.env()).env);
 useEffect(()=>{let alive=true;Promise.all([settingsApi.config(),settingsApi.schema(),settingsApi.env()]).then(([c,s,e])=>{if(alive){setConfig(c.config);setSchema(s);setEnv(e.env);setLoading(false)}}).catch(()=>{if(alive){setError('Không tải được cấu hình Hermes.');setLoading(false)}});return()=>{alive=false}},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[onClose]);
 const save=async(name:string,value:unknown)=>{await settingsApi.saveConfig(setPath({},name,value));setConfig(v=>setPath(v,name,value))};
 return <div className="settings-overlay" role="dialog" aria-modal="true" aria-label="Cài đặt Hermes"><header><button onClick={onClose} aria-label="Đóng cài đặt">←</button><div><b>Cài đặt</b><small>Hermes source of truth</small></div><button className="settings-close" onClick={onClose}>Đóng</button></header><div className="settings-layout"><nav>{SETTINGS_SECTIONS.map(s=><button key={s.id} className={s.id===active?'active':''} onClick={()=>setActive(s.id)}><i>{s.icon}</i><span>{s.label}</span>{s.credentials&&<em>{Object.values(env).filter(x=>x.is_set&&!x.channel_managed).length}</em>}</button>)}</nav><main>{loading?<div className="settings-loading">Đang đọc cấu hình Hermes…</div>:error?<div className="settings-error">{error}</div>:section.id==='appearance'?<Appearance/>:section.credentials?<Credentials env={env} reload={reloadEnv}/>:section.provider?<><div className="settings-lead"><h2>Providers</h2><p>Tài khoản provider và endpoint tùy chỉnh dùng chung với Hermes.</p></div><CustomEndpoints/><Credentials env={env} reload={reloadEnv}/></>:section.keys?<><div className="settings-lead"><h2>{section.label}</h2><p>Các thay đổi lưu trực tiếp vào config.yaml hiện tại.</p></div>{visibleFields(section,schema).map((name:string)=><ConfigField key={name} name={name} config={config} schema={schema} onSaved={save}/>)}</>:<DevicePanel section={section} sessions={sessions}/>}</main></div></div>}
